# frozen_string_literal: true

if Rails::VERSION::MAJOR == 7 && Rails::VERSION::MINOR == 2
  require_relative "behaviors_rails_7_2/cache_delete_matched_behavior"
  require_relative "behaviors_rails_7_2/cache_increment_decrement_behavior"
  require_relative "behaviors_rails_7_2/cache_instrumentation_behavior"
  require_relative "behaviors_rails_7_2/cache_logging_behavior"
  require_relative "behaviors_rails_7_2/cache_store_behavior"
  require_relative "behaviors_rails_7_2/cache_store_version_behavior"
  require_relative "behaviors_rails_7_2/cache_store_coder_behavior"
  require_relative "behaviors_rails_7_2/cache_store_compression_behavior"
  require_relative "behaviors_rails_7_2/cache_store_format_version_behavior"
  require_relative "behaviors_rails_7_2/cache_store_serializer_behavior"
  require_relative "behaviors_rails_7_2/connection_pool_behavior"
  require_relative "behaviors_rails_7_2/encoded_key_cache_behavior"
  require_relative "behaviors_rails_7_2/failure_safety_behavior"
  require_relative "behaviors_rails_7_2/failure_raising_behavior"
  require_relative "behaviors_rails_7_2/local_cache_behavior"
else
  require_relative "behaviors/cache_delete_matched_behavior"
  require_relative "behaviors/cache_increment_decrement_behavior"
  require_relative "behaviors/cache_instrumentation_behavior"
  require_relative "behaviors/cache_logging_behavior"
  require_relative "behaviors/cache_store_behavior"
  require_relative "behaviors/cache_store_version_behavior"
  require_relative "behaviors/cache_store_coder_behavior"
  require_relative "behaviors/cache_store_compression_behavior"
  require_relative "behaviors/cache_store_format_version_behavior"
  require_relative "behaviors/cache_store_serializer_behavior"
  require_relative "behaviors/connection_pool_behavior"
  require_relative "behaviors/encoded_key_cache_behavior"
  require_relative "behaviors/failure_safety_behavior"
  require_relative "behaviors/failure_raising_behavior"
  require_relative "behaviors/local_cache_behavior"
end
